server:
  port: ${SPRING_PORT}
spring:
  application:
    name: backend
  data:
    jpa.repositories.enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL12Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      generate-ddl: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 10
        order_updates: true
        batch_versioned_data: true
        default_schema: public
  sql:
    init:
      mode: always
      continue-on-error: true
